// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main #(
 parameter vac15e2 = 256
) (
 input va993b5,
 input [31:0] vfe4e9a,
 output [31:0] v5d0c90,
 output [0:7] vinit
);
 localparam p0 = vac15e2;
 wire w1;
 wire [0:31] w2;
 wire [0:31] w3;
 assign w1 = va993b5;
 assign v5d0c90 = w2;
 assign w3 = vfe4e9a;
 main_v0a05b1 #(
  .M(p0)
 ) v0a05b1 (
  .rst(w1),
  .out(w2),
  .pc(w3)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v0a05b1 #(
 parameter M = 0
) (
 input rst,
 input [31:0] pc,
 output [31:0] out
);
 reg [31:0]_o;
 reg ov;
 
 initial begin
     _o <= 0;
     ov <= 0;
 end
 
 always @(*) begin
     ov = (_o == M);
     if(rst | ov) begin
         _o <= 0;
     end else begin
         _o <= pc + 4;
     end
 end
 
 assign out = _o;
 
endmodule
