// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main #(
 parameter vac15e2 = 256
) (
 input v5d2dcc,
 input va993b5,
 input va0c046,
 output [31:0] v5d0c90,
 output [0:7] vinit
);
 localparam p0 = vac15e2;
 wire w1;
 wire w2;
 wire w3;
 wire [0:31] w4;
 assign w1 = v5d2dcc;
 assign w2 = va993b5;
 assign w3 = va0c046;
 assign v5d0c90 = w4;
 main_v0a05b1 #(
  .M(p0)
 ) v0a05b1 (
  .clk(w1),
  .rst(w2),
  .cnt(w3),
  .out(w4)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v0a05b1 #(
 parameter M = 0
) (
 input clk,
 input rst,
 input cnt,
 input [31:0] pc,
 output [31:0] out
);
 reg [31:0]_o;
 reg ov;
 
 initial begin
     _o <= 0;
     ov <= 0;
 end
 
 always @(posedge clk) begin
     ov = (_o == M);
     if(rst | ov) begin
         _o <= 0;
     end else begin
         _o <= pc + 4;
     end
 end
 
 assign out = _o;
 
endmodule
