// Code generated by Icestudio 0.7.0
// Wed, 08 Dec 2021 22:05:45 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // TODO: edit the module parameters here
 // e.g. localparam constant_value = 1;
 localparam constant_Memoria_Datos = "prueba.list";
 
 // Input/Output
 reg [31:0] Address;
 reg [31:0] Write_Data;
 reg Write;
 reg Read;
 reg clk;
 reg reset;
 wire [31:0] Read_Data;
 
 // Module instance
 main #(
  .v854d95(constant_Memoria_Datos)
 ) MAIN (
  .v9c7c2c(Address),
  .v57717b(Write_Data),
  .ve357ae(Write),
  .v19af5b(Read),
  .va196b8(clk),
  .ve480dc(reset),
  .vfb2d57(Read_Data)
 );
 
 // Clock signal
 always #0.5 clk = ~clk;
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  Address = 0;
  Write_Data = 0;
  Write = 0;
  Read = 0;
  clk = 0;
  reset = 0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
