// Code generated by Icestudio 0.7.0
// Thu, 30 Dec 2021 15:14:24 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 31;
 
 // Input/Output
 reg clk;
 reg reset;
 wire halt;
 
 // Module instance
 main MAIN (
  .vb5a909(clk),
  .v3abc7c(reset),
  .v2521b4(halt)
 );
 
 // Clock signal
 always #0.5 clk = ~clk;
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  clk = 0;
  reset = 0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
