// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main (
 input [31:0] va7e1cb,
 input [31:0] v4486d9,
 output [31:0] v49375d,
 output [0:7] vinit
);
 wire [0:31] w0;
 wire [0:31] w1;
 wire [0:31] w2;
 assign w0 = va7e1cb;
 assign w1 = v4486d9;
 assign v49375d = w2;
 main_v2322bc v2322bc (
  .in_1(w0),
  .in_2(w1),
  .out(w2)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v2322bc (
 input [31:0] in_1,
 input [31:0] in_2,
 output [31:0] out
);
 assign out = in_1 + in_2;
endmodule
