// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main (
 output [0:7] vinit
);
 main_v00bd94 v00bd94 (
 
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*-- ALU  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- ALU
/*-------------------------------------------------*/

module main_v00bd94 (
 input [31:0] A,
 input [31:0] B,
 input [3:0] Op,
 output [31:0] Result,
 output Z
);
 //-- Address bus
 wire signed [31:0] A;
 wire signed [31:0] B;
 wire [3:0]  Op;
 
 //-- Data bus
 reg [31:0]  Result = 0;
 reg Z;
 
 always @(*) begin
     case (Op)
         0   :   Result = A & B;
         1   :   Result = A | B;
         2   :   Result = A + B;
         6   :   Result = A - B;
         7   :   if(A < B) begin
                     Result = 1;
                 end else begin
                     Result = 0;
                 end
         12  :   Result = ~(A | B);
         default : Result = 0;
     endcase
     if(Result == 0) begin
         Z = 1;
     end else begin
         Z = 0;
     end
 end
endmodule
