// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main (
 input [31:0] vf36d91,
 output [5:0] ve46738,
 output [4:0] v58c5d0,
 output [4:0] vaa7a52,
 output [4:0] va9e58a,
 output [5:0] vffb721,
 output [15:0] vf728ca,
 output [25:0] vcea0f4,
 output [0:7] vinit
);
 wire [0:25] w0;
 wire [0:15] w1;
 wire [0:5] w2;
 wire [0:4] w3;
 wire [0:4] w4;
 wire [0:4] w5;
 wire [0:5] w6;
 wire [0:31] w7;
 assign vcea0f4 = w0;
 assign vf728ca = w1;
 assign vffb721 = w2;
 assign va9e58a = w3;
 assign vaa7a52 = w4;
 assign v58c5d0 = w5;
 assign ve46738 = w6;
 assign w7 = vf36d91;
 main_v161ee7 v161ee7 (
  .dir_2(w0),
  .dir_1(w1),
  .funtion(w2),
  .rd(w3),
  .rt(w4),
  .rs(w5),
  .inst(w6),
  .instruction(w7)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v161ee7 (
 input [31:0] instruction,
 output [5:0] inst,
 output [4:0] rs,
 output [4:0] rt,
 output [4:0] rd,
 output [5:0] funtion,
 output [15:0] dir_1,
 output [25:0] dir_2
);
 assign inst = instruction[31:26];
 
 assign rs = instruction[25:21];
 
 assign rt = instruction[20:16];
 
 assign rd = instruction[15:11];
 
 assign funtion = instruction[5:0];
 
 assign rd = instruction[15:0];
 
 assign rd = instruction[25:0];
endmodule
