// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main (
 input ve70352,
 input vd1d1c6,
 input v51a33d,
 input [4:0] v92bf35,
 input [31:0] v7d4d05,
 input [4:0] v630828,
 input [4:0] v162198,
 output [31:0] v70ed7b,
 output [31:0] vff4be9,
 output [0:7] vinit
);
 wire w0;
 wire [0:31] w1;
 wire [0:31] w2;
 wire w3;
 wire w4;
 wire [0:31] w5;
 wire [0:4] w6;
 wire [0:4] w7;
 wire [0:4] w8;
 assign w0 = vd1d1c6;
 assign v70ed7b = w1;
 assign vff4be9 = w2;
 assign w3 = ve70352;
 assign w4 = v51a33d;
 assign w5 = v7d4d05;
 assign w6 = v92bf35;
 assign w7 = v630828;
 assign w8 = v162198;
 main_v31ef17 v31ef17 (
  .reset(w0),
  .Read_Data_1(w1),
  .Read_Data_2(w2),
  .clk(w3),
  .write(w4),
  .Write_Data(w5),
  .Write_Reg(w6),
  .Read_Reg_1(w7),
  .Read_Reg_2(w8)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v31ef17 (
 input clk,
 input reset,
 input write,
 input [4:0] Write_Reg,
 input [31:0] Write_Data,
 input [4:0] Read_Reg_1,
 input [4:0] Read_Reg_2,
 output [31:0] Read_Data_1,
 output [31:0] Read_Data_2
);
 // Memory 
 reg [31:0] Mem [0:31];
 
 // Address Memory
 wire [4:0] Read_Reg_1;
 wire [4:0] Read_Reg_2;
 wire [4:0] Write_Reg;
 
 // Input control
 wire reset;
 wire clk;
 wire write;
 
 // Output Read Reg Data
 reg [31:0] Read_Data_1;
 reg [31:0] Read_Data_2;
 
 // Input Write Data
 wire [31:0] Write_Data;
 
 always @(posedge clk or posedge reset)
 begin
     if(reset != 0) begin
         for (i = 1; i < 32; i = i + 1) begin
             Mem[i] <= 32'b0;
         end
     end else if (write == 1 && Write_Reg != 0) begin
         Mem[Write_Reg] <= Write_Data;
     end
 end
 
 integer i;
 
 always @(*) 
 begin
     if (reset != 0) begin
         Read_Data_1 <= 0;
         Read_Data_2 <= 0;
     end else begin
         if(Read_Reg_1 != 0)
             Read_Data_1 <= Mem[Read_Reg_1];
         else
             Read_Data_1 <= 0;
             
         if(Read_Reg_2 != 0)
             Read_Data_2 <= Mem[Read_Reg_2];
         else
             Read_Data_2 <= 0;
     end
 end
 
 initial begin
     for (i = 1; i < 32; i = i + 1) begin
             Mem[i] <= 32'b0;
     end
 end
endmodule
