// Code generated by Icestudio 0.6.0

`default_nettype none

//---- Top entity
module main (
 input [31:0] v07286e,
 output [7:0] v5c1ea5,
 output [7:0] v60559c,
 output [7:0] v799988
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:31] w3;
 assign v799988 = w0;
 assign v5c1ea5 = w1;
 assign v60559c = w2;
 assign w3 = v07286e;
 main_v9b30bf v9b30bf (
  .C(w0),
  .B(w1),
  .A(w2),
  .In(w3)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v9b30bf (
 input [31:0] In,
 output [7:0] A,
 output [7:0] B,
 output [7:0] C
);
 assign A = In[23:16];
 assign B = In[15:8];
 assign C = In[7:0];
endmodule
