// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main (
 input [31:0] vf330bb,
 output [31:0] v7b0b31,
 output [0:7] vinit
);
 wire [0:31] w0;
 wire [0:31] w1;
 assign w0 = vf330bb;
 assign v7b0b31 = w1;
 main_v9d46af v9d46af (
  .A(w0),
  .I(w1)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v9d46af (
 input [31:0] A,
 output [31:0] I
);
 // Instruction Bus (32 bits)
 reg [31:0] I;
 // Memory Instruction
 reg [31:0] ins [0:63];
 
 parameter INSTROMFILE = "instruction.list";
 
 always @(*) begin
    I <= ins[A[31:2]];
 end
 
 // Memory contents read
 // from the INSTROMFILE table
 initial begin
     if (INSTROMFILE) $readmemh(INSTROMFILE, ins);
 end
endmodule
