// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main (
 input [31:0] ve99b4a,
 output [31:0] v9cfdd2,
 output [0:7] vinit
);
 wire [0:31] w0;
 wire [0:31] w1;
 assign w0 = ve99b4a;
 assign v9cfdd2 = w1;
 main_v5bddd1 v5bddd1 (
  .in(w0),
  .out(w1)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v5bddd1 (
 input [31:0] in,
 output [31:0] out
);
 reg [31:0]dout;
 
 initial begin
     dout <= 0;
 end
 
 always @(*) begin
     dout <= {in[29:0], in[31:30]};
 end
 
 assign out = dout;
endmodule
